### ISSUE TITLE
Hunter Agility Scaling: 2AGI : 1AP

### ISSUE THREAD

**Issue by whammyresilience** [momentum-wow/Momentum-Bugtracker#4]
Description: Visually Hunters appear to only gain 1 AP from agility scaling

Current behavior: Visually Hunters appear to only gain 1 AP from agility scaling

Expected behavior: Hunters should scale 2AP for every 1 point of Agi
https://docs.google.com/spreadsheets/d/1K-3ciY1BTAAVHruQ9BRrdjQyJp-abPfhS_6Cy3bqOGs/edit#gid=1276840054 (At the bottom)

Steps to reproduce the problem:
Equip an item with Agi, note the AP, remove the item, see that it is only 1 AP per 1 point of Agi

**Comment by Spellbreaker-Momentum** [comment]
Dunno if u r blind or just me.. but your Link even says... 1Agi = 1 AP.
That scaling you are talking about was pre Naxx in Classic. With T3 they changed the scaling cause it would be to OP.

**Comment by whammyresilience** [comment]
That’s why I closed it. Realized my mistake. 

No reason to be rude about it.

Thanks.

**Comment by Spellbreaker-Momentum** [comment]
Didnt ment to be rude ;)
